module.exports = {
    'ID'            : 'oracleId',
    'BRANCHID'      : 'branchId',
    'OVERALLRANK'   : 'overallRank',
    'CANCELSTATUS'  : 'cancelStatus',
    'ORDERGROUP'    : 'orderGroup',
    'ORDERTYPE'     : 'orderType',
    'BRANCHNAME'    : 'branchName',
    'CUSTOMERGROUP' : 'customerGroup',
    'CUSTOMERNUMBER': 'customerNumber',
    'CUSTOMERNAME'  : 'customerName',
    'CUSTOMERRANK'  : 'customerRank',
    'SHIPTOADDRESS1': 'shipToAddress1',
    'SHIPTOADDRESS2': 'shipToAddress2',
    'SHIPTOADDRESS3': 'shipToAddress3',
    'SHIPTOADDRESS4': 'shipToAddress4',
    'SHIPTOCITY'    : 'shipToCity',
    'SHIPTOSTATE'   : 'shipToState',
    'SHIPTOZIP'     : 'shipToZip',
    'BILLTOADDRESS1': 'billToAddress1',
    'BILLTOADDRESS2': 'billToAddress2',
    'BILLTOADDRESS3': 'billToAddress3',
    'BILLTOADDRESS4': 'billToAddress4',
    'BILLTOCITY'    : 'billToCity',
    'BILLTOSTATE'   : 'billToState',
    'BILLTOZIP'     : 'billToZip',
    'ORDERNUMBER'   : 'orderNumber',
    'DELIVERYNUM'   : 'deliveryNum',
    'ORDERDATE'     : 'orderDate',
    'DUEDATE'       : 'dueDate',
    'RELEASEDDATE'  : 'releasedDate',
    'REMARKS'       : 'remarks',
    'PONUM'         : 'poNum',
    'CREATEDBY'     : 'createdBy',
    'SHIPVIA'       : 'shipVia',
    'CARRIER'       : 'carrier',
    'UPDATEDSHIPVIA': 'updatedShipvia',
    'FREIGHTTERMS'  : 'freightTerms',
    'POAMOUNT'      : 'poAmount',
    'SOAMOUNT'      : 'soAmount',
    'CBF'           : 'cbf',
    'WEIGHT'        : 'weight',
    'PIECES'        : 'pieces'
};